version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postsPosts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postsPosts -U root"]
      interval: 5s
      timeout: 20s
      retries: 100

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/postsPosts?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

    # entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    entrypoint: ["/app/start.sh"]
    command: ["/app/main"]
