// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Post struct {
	Title string `json:"title"`
	Body  string `json:"body"`
	Owner string `json:"owner"`
}
